version: 2

jobs:
  build:
    working_directory: ~/smashing
    environment:
      LIBRARY: feedyard
      CONTAINER_NAME: smashing
      VERSION: 1.1.0
      BASH_ENV: local.env
    docker:
      - image: feedyard/circleci-remote-docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: confirm Docker
          command: docker info
      - run:
          name: decrypt secrets
          command: invoke dec
      - run:
          name: build image
          command: docker build -t $LIBRARY/$CONTAINER_NAME:latest .
      - run:
          name: tag with build version
          command: docker tag $LIBRARY/$CONTAINER_NAME:latest $LIBRARY/$CONTAINER_NAME:$VERSION.$CIRCLE_BUILD_NUM
      - run:
          name: configuration tests
          command: |
            inspec exec profiles/cis-docker
            CID="$(docker run -it -d $LIBRARY/$CONTAINER_NAME:latest ash)"
            inspec exec profiles/smashing/ -t docker://$CID
            docker rm -f $CID
      - deploy:
          name: deploy to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $LIBRARY/$CONTAINER_NAME:$VERSION.$CIRCLE_BUILD_NUM
            docker push $LIBRARY/$CONTAINER_NAME:latest
            docker login -u=$FEEDYARD_QUAYIO_ROBOT_USER -p=$FEEDYARD_QUAYIO_ROBOT_USER_TOKEN quay.io
            docker push $LIBRARY/$CONTAINER_NAME:$VERSION.$CIRCLE_BUILD_NUM
            docker push $LIBRARY/$CONTAINER_NAME:latest